export const paths = {
  root: '/',
  addEcts: '/ects/create',
  login: 'auth/login',
  profile: 'admin/profile',
  majorsScraper: 'majors/scraper',
  createMajor: '/majors/create',
  majors: '/majors',
  majorDetails: '/majors/:id',
  majorsEdit: '/majors/edit/:id',
  ects: 'ects',
  news: 'news',
  newsCreate: 'news/form',
  newsDetails: 'news/:id',
  newsEdit: 'news/edit/:id',
  lessonsCreate: 'lessons/form',
  lessons: 'lessons',
  lessonsDetails: 'lessons/:id',
  lessonsEdit: 'lessons/edit/:id',
  staff: 'staff',
  staffScraper: 'staff/scraper',
  staffCreate: 'staff/form',
  staffDetails: 'staff/:id',
  staffEdit: 'staff/edit/:id',
  events: 'events',
};
