export const paths = {
  root: '/',
  majors: '/majors/scraper',
  addEcts: '/ects/create',
  login: 'auth/login',
  profile: 'admin/profile',
  majorsScraper: 'majors/scraper',
  createMajor: '/majors/create',
  ects: 'ects',
  news: 'news',
  newsCreate: 'news/form',
  newsDetails: 'news/:id',
  newsEdit: 'news/edit/:id',
  lessons: 'lessons',
  staff: 'staff',
  staffCreate: 'staff/form',
  staffDetails: 'staff/:id',
  staffEdit: 'staff/edit/:id',
};
